# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Test

  variables:
  - name: inventory
    value: veos_vtb
  - name: testbed_file
    value: vtestbed.csv

  jobs:
  - job: part1
    pool: sonictest
    displayName: "kvmtest-t0-part1"
    timeoutInMinutes: 200

    steps:
    - template: .azure-pipelines/run-test-template.yml
      parameters:
        dut: vlab-01
        tbname: vms-kvm-t0
        ptf_name: ptf_vms6-1
        tbtype: t0
        vmtype: ceos
        section: part-1

  - job: part2
    pool: sonictest
    displayName: "kvmtest-t0-part2"
    timeoutInMinutes: 200

    steps:
    - template: .azure-pipelines/run-test-template.yml
      parameters:
        dut: vlab-01
        tbname: vms-kvm-t0
        ptf_name: ptf_vms6-1
        tbtype: t0
        vmtype: ceos
        section: part-2

  - job:
    displayName: "kvmtest-t0"
    timeoutInMinutes: 400
    dependsOn:
    - part1
    - part2
    variables:
      resultOfPart1: $[ dependencies.part1.result ]
      resultOfPart2: $[ dependencies.part2.result ]

    steps:
    - script: 'echo "Both job kvemtest-t0-part1 and kvemtest-t0-part2 are passed."'
      condition: |
        and
        (
          in(variables.resultOfPart1, 'Succeeded'),
          in(variables.resultOfPart2, 'Succeeded')
        )

    - script: 'echo "Either job kvemtest-t0-part1 or job kvemtest-t0-part2 failed! Please check the detailed information." ; exit 1'
      condition: |
        or
        (
          notIn(variables.resultOfPart1, 'Succeeded'),
          notIn(variables.resultOfPart2, 'Succeeded')
        )

  - job:
    pool: sonictest-t1-lag
    displayName: "kvmtest-t1-lag"
    timeoutInMinutes: 240

    steps:
    - template: .azure-pipelines/run-test-template.yml
      parameters:
        dut: vlab-03
        tbname: vms-kvm-t1-lag
        ptf_name: ptf_vms6-2
        tbtype: t1-lag
        vmtype: ceos

  - job:
    pool: sonictest-sonic-t0
    displayName: "kvmtest-t0-sonic"
    timeoutInMinutes: 240

    steps:
    - template: .azure-pipelines/run-test-template.yml
      parameters:
        dut: vlab-01
        tbname: vms-kvm-t0
        ptf_name: ptf_vms6-1
        tbtype: t0-sonic
        vmtype: vsonic
